apiVersion: apps/v1
kind: Deployment
metadata:
  name: shrtnr
spec:
  selector:
    matchLabels:
      app: shrtnr
  replicas: 2
  template:
    metadata:
      labels:
        app: shrtnr
        step: staging
    spec:
      containers:
      - name: shrtnr
        imagePullPolicy: Always
        image: lackerman/shrtnr:LATEST_COMMIT
        ports:
        - containerPort: 8080